### ISSUE TITLE
v0.1.0 LGF Rewrite Roadmap

### ISSUE THREAD

**Issue by srevrtt** [lua-graphics-framework/lgf-rewrite#1]
This issue contains the v0.1.0 roadmap for the new, more polished, and more complete LGF. This rewrite is being written in C.

## Why?

This is a very good question. The main reason why I am rewriting LGF is because the current library is built on top of a very old and very "bad" codebase I developed when I didn't know what I was doing. Another reason is that the current implementation of LGF is built on top of SDL2, meaning that LGF is currently a graphics framework on top of a graphics framework. **The rewrite's code will be using OpenGL for all platforms at the beginning.** Then, once the codebase gets stable, Metal could be used on Apple devices, WebGPU could be used for the web, and OpenGL ES could be used on Android. I guess after that, there could be a sort of plugin system so the community (which will hopefully exist by then..) could write other backends for other game consoles. **Essentially, all it boils down to is long term sustainability.**

## Roadmap

Note that multiple tasks may be worked on at once.
Cross platform currently means Windows, macOS, and Linux.

### Windowing & Graphics

- [ ] Cross platform window creation from native APIs
- [ ] Cross platform OpenGL context creation
- [ ] Simple math interface for working with matrices and vectors
- [ ] Transformable rectangle rendering
- [ ] Image loading & rendering with stb_image
- [ ] Single pixel rendering
- [ ] Image color modifications
- [ ] Image & rectangle blending for transparency
- [ ] Font loading & rendering with Freetype

### Input

- [ ] Cross platform keyboard input
- [ ] Cross platform mouse position "grabbing"
- [ ] Cross platform mouse button events
- [ ] Cross platform joystick input
- [ ] Cross platform touch screen input

### Other

- [ ] Sound & music playback
- [ ] Utility functions module
